package tw.oresplus.enums;

import net.minecraft.item.Item;

public enum OreItems {
	crushedAdamantine,
	crushedColdiron,
	crushedCopper,
	crushedLead,
	crushedMithral,
	crushedNickel,
	crushedPlatinum,
	crushedSilver,
	crushedTin,
	crushedZinc,
	dustAdamantine, 
	dustAluminium,
	dustBauxite, // TODO: Update texture
	dustBrass, 
	dustBronze, 
	dustCassiterite, // TODO: Update texture
	dustCharcoal, 
	dustCinnabar,
	dustCoal, 
	dustColdiron, 
	dustCopper, 
	dustElectrum,
	dustGalena, // TODO: Update texture
	dustGold, 
	dustIron, 
	dustLead, 
	dustMagnesium,
	dustManganese, // TODO: Update texture
	dustMithral, 
	dustNickel, 
	dustNikolite,
	dustPhosphorite,
	dustPlatinum, 
	dustPotash,
	dustPyrite,
	dustSaltpeter,
	dustSheldonite, // TODO: Update texture
	dustSilver, 
	dustSodalite,
	dustSphalerite,
	dustSulfur,
	dustTetrahedrite, // TODO: Update texture
	dustTin, 
	dustTungstate, // TODO: Update texture
	dustTungsten, // TODO: Update texture
	dustZinc,
	gemAmethyst,
	gemApatite,
	gemGreenSapphire,
	gemIridium,
	gemOlivine,
	gemRedGarnet,
	gemRuby,
	gemSapphire,
	gemTopaz,
	gemUranium,
	gemYellowGarnet,
	itemBitumen,
	ingotAdamantine,
	ingotBrass, 
	ingotBronze, 
	ingotColdiron,
	ingotCopper,
	ingotElectrum,
	ingotLead,
	ingotMithral,
	ingotNickel,
	ingotPlatinum,
	ingotSilver,
	ingotTin,
	ingotZinc,
	nuggetAdamantine,
	nuggetBrass,
	nuggetBronze,
	nuggetColdiron,
	nuggetCopper,
	nuggetElectrum,
	nuggetLead,
	nuggetMithral,
	nuggetNickel,
	nuggetPlatinum,
	nuggetSilver,
	nuggetTin,
	nuggetZinc;	 
}
